apiVersion: v1
kind: Service
metadata:
  name: seed
  labels:
    version: ${VERSION}
spec:
  selector:
    app: seed
    version: ${VERSION}
  ports:
  - port: 9876
    targetPort: 9876
    name: p2p
    protocol: TCP
