apiVersion: v1
kind: Service
metadata:
  name: wallet
  labels:
    version: ${VERSION}
spec:
  selector:
    app: wallet
    version: ${VERSION}
  ports:
  - port: 8888
    targetPort: 8888
    name: p2p
    protocol: TCP
